name: Client CI

on:
  push:
    branches: [gh-pages]
    paths: 
      -  client/**
      - .github/workflows/client-ci.yml
permissions:
  contents: write
jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Checkout"
        uses: actions/checkout@v3
      
      - name: "Install and Build"
        run: |
          cd client
          npm i
          npm run build
      - 
        name: "Deploy 🚀"
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: client/build
