name: Client CI

on:
  push:
    branches: [master]
    paths: 
      -  client/**
      - .github/workflows/client-ci.yml
permissions:
  contents: write
env:
  TOTAL_SUPPLY: ${{ secrets.TOTAL_SUPPLY }}
  RATE: ${{ secrets.RATE }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  ALCHEMY_GOERLI: ${{ secrets.ALCHEMY_GOERLI }}
jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - 
        name: "Checkout Truffle"
        uses: actions/checkout@v3
      
      - name: "Install and Build"
        run: |
          cd truffle
          npm install -g truffle
          npm install -g ganache-cli
          npm i
      
      - name: "Run Ganache CLI"
        run: |
          ganache-cli -p 8545 --gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 1000000000 > /dev/null & while netstat -lnt | awk '$4 ~ /:8545$/ {exit 1}'; do sleep 5; done
      
      - name: "Run Truffle Testing"
        run: |
          cd truffle
          truffle test
      
      - name: "Run Migrate"
        run: |
          cd truffle
          truffle migrate --network goerli
          chmod +x pos-deploy.sh
          ./pos-deploy.sh
          kill $(lsof -t -i:8545)

      - name: "Deploy Lambda"
        run: |
          cd sign_on_rust
          rustup target add x86_64-unknown-linux-musl
      - name: "Build"
        run: |
          cd sign_on_rust
          cargo build --release --target x86_64-unknown-linux-musl
      - name: "Create .zip file"
        run: |
          cd sign_on_rust
          cp target/x86_64-unknown-linux-musl/release/assign_on_rust bootstrap
          zip lambda.zip bootstrap
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-east-1
      - name: deploy
        run: |
            cd sign_on_rust
            aws lambda update-assign_on_rust --function-name=assign_on_rust --zip-file=fileb://lambda.zip
      # - name: "Frontend Install and Build"
      #   run: |
      #     cd client
      #     npm i
      #     npm run build
      # - 
      #   name: "Deploy Frontend 🚀"
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with: 
      #     folder: client/build