name: Client CI

on:
  push:
    branches: [master]
    paths: 
      -  client/**
      - .github/workflows/client-ci.yml
permissions:
  contents: write
env:
  TOTAL_SUPPLY: ${{ secrets.TOTAL_SUPPLY }}
  RATE: ${{ secrets.RATE }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  ALCHEMY_GOERLI: ${{ secrets.ALCHEMY_GOERLI }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  IAM_ROLE: ${{ secrets.IAM_ROLE }}
jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - 
        name: "Checkout Truffle"
        uses: actions/checkout@v3
      
      - name: "Install and Build"
        run: |
          cd truffle
          npm install -g truffle
          npm install -g ganache-cli
          npm i
      
      - name: "Run Ganache CLI"
        run: |
          ganache-cli -p 8545 --gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 1000000000 > /dev/null & while netstat -lnt | awk '$4 ~ /:8545$/ {exit 1}'; do sleep 5; done
      
      - name: "Run Truffle Testing"
        run: |
          cd truffle
          truffle test
      
      - name: "Run Migrate"
        run: |
          cd truffle
          truffle migrate --network goerli
          chmod +x pos-deploy.sh
          ./pos-deploy.sh
          kill $(lsof -t -i:8545)

      - name: "Deploy Lambda"
        run: |
          cd sign_on_rust
          rustup target add x86_64-unknown-linux-gnu
      
      - name: "Build"
        run: |
          cd sign_on_rust
          cargo install cargo-lambda
          cargo lambda build --release --target x86_64-unknown-linux-gnu

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        run: |
            cd sign_on_rust
            cargo lambda deploy --iam-role $IAM_ROLE
      - name: "Frontend Install and Build"
        run: |
          cd client
          npm i
          npm run build
      - 
        name: "Deploy Frontend 🚀"
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: client/build