name: Client CI

on:
  push:
    branches: [master]
    paths: 
      -  client/**
      - .github/workflows/client-ci.yml
permissions:
  contents: write
env:
  TOTAL_SUPPLY: ${{ secrets.TOTAL_SUPPLY }}
  RATE: ${{ secrets.RATE }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  ALCHEMY_GOERLI: ${{ secrets.ALCHEMY_GOERLI }}
jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - 
        name: "Checkout Truffle"
        uses: actions/checkout@v3
      
      - name: "Install and Build"
        run: |
          cd truffle
          npm install -g truffle
          npm install -g ganache-cli
          npm i
      
      - name: "Run Ganache CLIs"
        run: |
          ganache-cli -p 8545 --gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 1000000000 > /dev/null & while netstat -lnt | awk '$4 ~ /:8545$/ {exit 1}'; do sleep 5; done
      
      - name: "Run Truffle Test"
        run: |
          cd truffle
          echo $TOTAL_SUPPLY
          echo $MNEMONIC
          echo $RATE
          truffle test
      
      - name: "Run Migrate"
        run: |
          cd truffle
          truffle migrate --network goerli
      - 
        name: "Checkout Frontend"
        uses: actions/checkout@v3
      
      - name: "Install and Build"
        run: |
          cd client
          npm i
          npm run build
      - 
        name: "Deploy 🚀"
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: client/build
