--- 
contents: write
jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Use Node.js 16"
        uses: actions/checkout@v2
        with: 
          node-version: 16.x
          run: |
              npm i
              npm run build
      - 
        name: "Deploy 🚀"
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: build
name: "Client CI"
permissions: ~
true: 
   push:
    branches:
      - gh-pages
    paths: 
      - client/**
      - .github/workflows/client-ci.yml
